services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:8000
    networks:
      - medic_network
    restart: on-failure

networks:
  medic_network:
    driver: bridge
